name: deploy etl pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-central-1
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: setup s3 backend
        run: |
          cd infrastructure
          sh setting_up_state_s3.sh
      - name: building lambda source codes
        run: |
          cd src
          sh build_source_code.sh
      - name: deploy whole infrastructure via hcl
        run: |
          cd infrastructure
          terraform init
          terraform apply -auto-approve
